version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USERNAME}/ui:${UIVER}
    ports:
      - ${HOSTPORT}:${APPPORT}/tcp
    networks:
      - front_net
  post:
    image: ${USERNAME}/post:${POSTVER}
    networks:
      - front_net
      - back_net
  comment:
    image: ${USERNAME}/comment:${COMMETNVER}
    networks:
      - front_net
      - back_net

volumes:
  post_db:
  prometheus_data:

networks:
  front_net:
    ipam:
      config:
        - subnet: 10.0.1.0/24
  back_net:
    ipam:
      config:
        - subnet: 10.0.2.0/24
